sudo: required
services:
    - docker
    
before_install:
    - docker build -t mariathar/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true mariathar/docker-react npm run test

deploy:
    provider: elastickbeanstalk
    region: "us-east-2"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-east-2-578048377849"
    bucket_path: "docker"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY